# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caratteristica',
            fields=[
                ('codice', models.CharField(db_column='CODICE', max_length=3, primary_key=True, serialize=False, verbose_name='Codice')),
                ('descrizione', models.CharField(db_column='DESCRIZION', max_length=50, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Caratteristiche',
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('codice', models.IntegerField(db_column='CODICE', primary_key=True, serialize=False, verbose_name='Codice')),
                ('descrizione', models.CharField(db_column='DESCRIZION', max_length=250, verbose_name='Descrizione')),
                ('immagine', models.ImageField(db_column='IMMAGINE', upload_to='', verbose_name='Immagine')),
            ],
        ),
        migrations.CreateModel(
            name='Condizioni',
            fields=[
                ('codice', models.CharField(db_column='CODICE', max_length=2, primary_key=True, serialize=False, verbose_name='Codice')),
                ('descrizione', models.CharField(db_column='DESCRIZION', max_length=16, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Condizioni',
            },
        ),
        migrations.CreateModel(
            name='Difficolta',
            fields=[
                ('codice', models.CharField(db_column='CODICE', max_length=3, primary_key=True, serialize=False, verbose_name='Codice')),
                ('descrizione', models.CharField(db_column='DESCRIZION', max_length=20, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Difficoltà',
            },
        ),
        migrations.CreateModel(
            name='Forra',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='Id Forra')),
                ('nome', models.CharField(db_column='TREK1', max_length=80, verbose_name='Nome Forra')),
                ('verticalita', models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], db_column='LIVVER', decimal_places=0, max_digits=1, verbose_name='Livello Verticalità')),
                ('acquaticita', models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], db_column='LIVH2O', decimal_places=0, max_digits=1, verbose_name='Livello Acquaticità')),
                ('bellezza', models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], db_column='LIVBEL', decimal_places=0, max_digits=1, verbose_name='Punteggio Bellezza')),
                ('divertimento', models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], db_column='LIVDIV', decimal_places=0, max_digits=1, verbose_name='Punteggio Divertimento')),
                ('numero_calate', models.DecimalField(db_column='NUMC', decimal_places=0, max_digits=1, verbose_name='Numero Calate')),
                ('calata_massima', models.DecimalField(db_column='CALMAX', decimal_places=0, max_digits=1, verbose_name='Calata Massima')),
                ('lunghezza_min_corda', models.DecimalField(db_column='CORMIN', decimal_places=0, max_digits=2, verbose_name='Lunghezza minima corda singola')),
                ('numero_min_corde', models.DecimalField(db_column='MINCORDE', decimal_places=0, max_digits=1, verbose_name='Numero minimo di corde')),
                ('dislivello', models.DecimalField(db_column='DISLIV', decimal_places=0, max_digits=2, verbose_name='Dislivello')),
                ('ampiezza_bacino', models.DecimalField(db_column='AMPBAC', decimal_places=0, max_digits=4, verbose_name='Ampiezza Bacino (km2)')),
                ('ore_avvicinamento', models.DecimalField(db_column='HAVV', decimal_places=2, max_digits=5, verbose_name='Ore Avvicinamento')),
                ('ore_discesa', models.DecimalField(db_column='HCAL', decimal_places=2, max_digits=5, verbose_name='Ore Discesa')),
                ('ore_rientro', models.DecimalField(db_column='HRIE', decimal_places=2, max_digits=5, verbose_name='Ore Rientro')),
                ('minuti_navetta', models.DecimalField(db_column='MMNAV', decimal_places=0, max_digits=3, verbose_name='Minuti Navetta')),
                ('km_navetta', models.DecimalField(db_column='KMNAV', decimal_places=0, max_digits=3, verbose_name='Kilometri Navetta')),
                ('vincoli_ambientali', models.TextField(db_column='VINCOLI', max_length=250, null=True, verbose_name='Vincoli ambientali')),
                ('presentazione_forra', models.TextField(db_column='PRES', max_length=250, null=True, verbose_name='Presentazione forra')),
                ('descr_accesso_valle', models.TextField(db_column='DESACCV', max_length=250, null=True, verbose_name='Descrizione accesso a valle')),
                ('descr_accesso_monte', models.TextField(db_column='DESACCM', max_length=250, null=True, verbose_name='Descrizione accesso a monte')),
                ('descr_avvicinamento', models.TextField(db_column='DESAVV', max_length=250, null=True, verbose_name='Descrizione avvicinamento')),
                ('descr_percorso', models.TextField(db_column='DESPERC', max_length=250, null=True, verbose_name='Descrizione percorso')),
                ('descr_uscita', models.TextField(db_column='DESUSC', max_length=250, null=True, verbose_name='Descrizione uscita')),
                ('profilo', models.ImageField(blank=True, db_column='PROFILO', upload_to='profili/', verbose_name='Profilo Forra')),
                ('note', models.TextField(db_column='NOTE', max_length=250, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'Forre',
            },
        ),
        migrations.CreateModel(
            name='GradoImpegno',
            fields=[
                ('codice', models.CharField(db_column='CODICE', max_length=2, primary_key=True, serialize=False, verbose_name='Codice')),
                ('descrizione', models.CharField(db_column='DESCRIZION', max_length=20, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Gradi Impegno',
            },
        ),
        migrations.CreateModel(
            name='Litologia',
            fields=[
                ('codice', models.IntegerField(db_column='CODICE', primary_key=True, serialize=False, verbose_name='Codice')),
                ('descrizione', models.CharField(db_column='DESCRIZION', max_length=20, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Litologie',
            },
        ),
        migrations.CreateModel(
            name='Mese',
            fields=[
                ('codice', models.IntegerField(db_column='CODICE', primary_key=True, serialize=False, verbose_name='Codice')),
                ('mese', models.CharField(db_column='MESE', max_length=10, verbose_name='Mese')),
            ],
            options={
                'verbose_name_plural': 'Mesi',
            },
        ),
        migrations.CreateModel(
            name='OperaIdraulica',
            fields=[
                ('codice', models.CharField(db_column='CODICE', max_length=2, primary_key=True, serialize=False, verbose_name='Codice')),
                ('descrizione', models.CharField(db_column='DESCRIZION', max_length=20, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Opere Idrauliche',
            },
        ),
        migrations.CreateModel(
            name='OrigineAcqua',
            fields=[
                ('codice', models.IntegerField(db_column='CODICE', primary_key=True, serialize=False, verbose_name='Codice')),
                ('descrizione', models.CharField(db_column='DESCRIZION', max_length=20, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Origini Acqua',
            },
        ),
        migrations.CreateModel(
            name='Percorso',
            fields=[
                ('id', models.IntegerField(db_column='IDPERC', primary_key=True, serialize=False, verbose_name='Id Percorso')),
                ('numero', models.CharField(db_column='NUME', max_length=6, verbose_name='Numero Percorso')),
                ('nome', models.CharField(db_column='TREK1', max_length=80, verbose_name='Nome/Sigla/Logo Trekking')),
                ('descrizione', models.CharField(db_column='DENOMI', max_length=80, null=True, verbose_name='Descrizione')),
                ('lunghezza_piana', models.DecimalField(db_column='PERLUN', decimal_places=0, max_digits=5, verbose_name='Lunghezza Piana')),
                ('lunghezza_inclinata', models.DecimalField(db_column='PERLUNF', decimal_places=0, max_digits=5, verbose_name='Lunghezza Inclinata')),
                ('quota_inizio', models.DecimalField(db_column='PERQUO1', decimal_places=0, max_digits=4, verbose_name='Quota Inizio')),
                ('quota_fine', models.DecimalField(db_column='PERQUO2', decimal_places=0, max_digits=4, verbose_name='Quota Fine')),
                ('pendenza', models.DecimalField(db_column='PENDENZA', decimal_places=2, max_digits=5, verbose_name='Pendenza')),
                ('tempo_andata', models.DecimalField(db_column='PERTEM1', decimal_places=2, max_digits=5, verbose_name='Tempo di percorrenza andata')),
                ('tempo_ritorno', models.DecimalField(db_column='PERTEM2', decimal_places=2, max_digits=5, verbose_name='Tempo di percorrenza ritorno')),
                ('data_aggiornamento', models.DateField(db_column='DATARIL', verbose_name='Data Aggiornamento')),
                ('codice_catasto', models.CharField(db_column='CODREG', max_length=12, null=True, verbose_name='Codice Catasto Regionale')),
                ('operatore', models.CharField(db_column='OPERATORE', max_length=80, verbose_name='Ente Manutentore')),
                ('link_CMS', models.CharField(db_column='LINK', max_length=16, null=True, verbose_name='Link CMS')),
                ('aggiornatore', models.CharField(db_column='UTENTE', max_length=16, null=True, verbose_name='Aggiornatore')),
                ('difficolta', models.ForeignKey(db_column='PERDIF', on_delete=django.db.models.deletion.CASCADE, to='infotor.Difficolta', verbose_name='Difficoltà')),
                ('percorribilita', models.ForeignKey(db_column='PERCORR', on_delete=django.db.models.deletion.CASCADE, to='infotor.Condizioni', verbose_name='Percorribilità')),
            ],
            options={
                'verbose_name_plural': 'Percorsi',
            },
        ),
        migrations.CreateModel(
            name='Percorso_Tratta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percorso', models.ForeignKey(db_column='ID_PERCORS', on_delete=django.db.models.deletion.CASCADE, to='infotor.Percorso', verbose_name='ID Percorso')),
            ],
        ),
        migrations.CreateModel(
            name='Segnaletica',
            fields=[
                ('codice', models.CharField(db_column='CODICE', max_length=3, primary_key=True, serialize=False, verbose_name='Codice')),
                ('descrizione', models.CharField(db_column='DESCRIZION', max_length=20, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Segnaletiche',
            },
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('codice', models.CharField(db_column='CODICE', max_length=3, primary_key=True, serialize=False, verbose_name='Codice')),
                ('descrizione', models.CharField(db_column='DESCRIZION', max_length=50, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Tipologie',
            },
        ),
        migrations.CreateModel(
            name='Tratta',
            fields=[
                ('id', models.IntegerField(db_column='IDTRAT', primary_key=True, serialize=False, verbose_name='Id Tratta')),
                ('nome', models.CharField(db_column='TRTNAME', max_length=30, null=True, verbose_name='Nome Tratta')),
                ('regione', models.CharField(db_column='REGIONE', max_length=2, null=True, verbose_name='Regione')),
                ('provincia', models.CharField(db_column='PROVINCIA', max_length=2, null=True, verbose_name='Provincia')),
                ('comune', models.CharField(db_column='COMUNE', max_length=6, null=True, verbose_name='Comune')),
                ('gruppo_montuoso', models.CharField(db_column='GRUMON', max_length=11, null=True, verbose_name='Gruppo Montuoso')),
                ('sezione', models.CharField(db_column='SEZION', max_length=7, null=True, verbose_name='Sezione')),
                ('lunghezza_piana', models.DecimalField(db_column='PERLUN', decimal_places=0, max_digits=5, verbose_name='Lunghezza Piana')),
                ('lunghezza_inclinata', models.DecimalField(db_column='PERLUNF', decimal_places=0, max_digits=5, verbose_name='Lunghezza Inclinata')),
                ('quota_inizio', models.DecimalField(db_column='PERQUO1', decimal_places=0, max_digits=4, verbose_name='Quota Inizio')),
                ('quota_fine', models.DecimalField(db_column='PERQUO2', decimal_places=0, max_digits=4, verbose_name='Quota Fine')),
                ('pendenza', models.DecimalField(db_column='PENDENZA', decimal_places=2, max_digits=5, verbose_name='Pendenza')),
                ('tempo_andata', models.DecimalField(db_column='NEWFIELD1', decimal_places=2, max_digits=5, verbose_name='Tempo di percorrenza andata')),
                ('tempo_ritorno', models.DecimalField(db_column='NEWFIELD2', decimal_places=2, max_digits=5, verbose_name='Tempo di percorrenza ritorno')),
                ('rilevatore', models.CharField(db_column='RILEVATORE', max_length=50, null=True, verbose_name='Rilevatore')),
                ('gps', models.CharField(db_column='DATA_GPS', max_length=16, null=True, verbose_name='Data GPS')),
                ('id_rilevatore', models.CharField(db_column='ID_RIL', max_length=3, null=True, verbose_name='ID Rilevatore')),
                ('caratteristica', models.ForeignKey(db_column='CARATTER', on_delete=django.db.models.deletion.CASCADE, to='infotor.Caratteristica', verbose_name='Caratteristica')),
                ('difficolta', models.ForeignKey(db_column='PERDIF', on_delete=django.db.models.deletion.CASCADE, to='infotor.Difficolta', verbose_name='Difficoltà')),
                ('segnaletica', models.ForeignKey(db_column='SEGNI', on_delete=django.db.models.deletion.CASCADE, to='infotor.Segnaletica', verbose_name='Segnaletica')),
                ('tipologia', models.ForeignKey(db_column='TIPOLOGIA', on_delete=django.db.models.deletion.CASCADE, to='infotor.Tipologia', verbose_name='Tipologia')),
            ],
            options={
                'verbose_name_plural': 'Tratte',
            },
        ),
        migrations.AddField(
            model_name='percorso_tratta',
            name='tratta',
            field=models.ForeignKey(db_column='ID_TRATTA', on_delete=django.db.models.deletion.CASCADE, to='infotor.Tratta', verbose_name='ID Tratta'),
        ),
        migrations.AddField(
            model_name='percorso',
            name='segnaletica',
            field=models.ForeignKey(db_column='SEGNI', on_delete=django.db.models.deletion.CASCADE, to='infotor.Segnaletica', verbose_name='Segnaletica'),
        ),
    ]
