# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-01 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0009_auto_20181228_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='forra',
            name='id_percorso',
            field=models.ForeignKey(db_column='IDPERC', default=0, on_delete=django.db.models.deletion.CASCADE, to='infotor.Percorso', verbose_name='Id Percorso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forra',
            name='id',
            field=models.IntegerField(db_column='NUME', primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
