# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0012_auto_20190306_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='forra',
            name='id_percorso',
            field=models.ForeignKey(db_column='IDPERC', default=0, on_delete=django.db.models.deletion.CASCADE, to='infotor.Percorso', verbose_name='Id Percorso'),
            preserve_default=False,
        ),
    ]
