# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0014_auto_20190307_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forra',
            name='ore_avvicinamento',
        ),
        migrations.RemoveField(
            model_name='forra',
            name='ore_rientro',
        ),
    ]
