# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0015_auto_20190307_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forra',
            name='tempo_andata',
            field=models.TimeField(blank=True, db_column='PERTEM1', null=True, verbose_name='Tempo di percorrenza andata'),
        ),
        migrations.AlterField(
            model_name='forra',
            name='tempo_ritorno',
            field=models.TimeField(blank=True, db_column='PERTEM2', null=True, verbose_name='Tempo di percorrenza ritorno'),
        ),
    ]
