# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0016_auto_20190307_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forra',
            name='tempo_andata',
            field=models.DecimalField(blank=True, db_column='PERTEM1', decimal_places=2, max_digits=5, null=True, verbose_name='Tempo di percorrenza andata'),
        ),
        migrations.AlterField(
            model_name='forra',
            name='tempo_ritorno',
            field=models.DecimalField(blank=True, db_column='PERTEM2', decimal_places=2, max_digits=5, null=True, verbose_name='Tempo di percorrenza ritorno'),
        ),
        migrations.AlterField(
            model_name='tratta',
            name='tempo_andata',
            field=models.IntegerField(db_column='NEWFIELD1', verbose_name='Tempo di percorrenza andata'),
        ),
        migrations.AlterField(
            model_name='tratta',
            name='tempo_ritorno',
            field=models.IntegerField(db_column='NEWFIELD2', verbose_name='Tempo di percorrenza ritorno'),
        ),
    ]
