# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import infotor.validators


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0018_auto_20190307_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forra',
            name='minuti_navetta',
            field=models.CharField(blank=True, db_column='MMNAV', max_length=5, null=True, validators=[infotor.validators.timespan_validator], verbose_name='Minuti Navetta'),
        ),
        migrations.AlterField(
            model_name='forra',
            name='ore_discesa',
            field=models.CharField(blank=True, db_column='HCAL', max_length=5, null=True, validators=[infotor.validators.timespan_validator], verbose_name='Ore Discesa'),
        ),
    ]
