# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-11 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0019_auto_20190307_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='codice',
            field=models.AutoField(db_column='CODICE', primary_key=True, serialize=False, verbose_name='Codice'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='descrizione',
            field=models.TextField(blank=True, db_column='DESCRIZION', max_length=250, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='immagine',
            field=models.ImageField(blank=True, db_column='IMMAGINE', null=True, upload_to='checkpoints/', verbose_name='Immagine'),
        ),
    ]
