# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-18 15:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import infotor.validators


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0020_auto_20190311_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forra',
            name='calata_massima',
            field=models.DecimalField(blank=True, db_column='CALMAX', decimal_places=0, max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calata Massima (m)'),
        ),
        migrations.AlterField(
            model_name='forra',
            name='lunghezza_inclinata',
            field=models.DecimalField(blank=True, db_column='PERLUNF', decimal_places=0, max_digits=5, null=True, verbose_name='Lunghezza Inclinata (km)'),
        ),
        migrations.AlterField(
            model_name='forra',
            name='lunghezza_min_corda',
            field=models.DecimalField(blank=True, db_column='CORMIN', decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lunghezza minima corda singola (m)'),
        ),
        migrations.AlterField(
            model_name='forra',
            name='lunghezza_piana',
            field=models.DecimalField(blank=True, db_column='PERLUN', decimal_places=0, max_digits=5, null=True, verbose_name='Lunghezza Piana (km)'),
        ),
        migrations.AlterField(
            model_name='forra',
            name='minuti_navetta',
            field=models.CharField(blank=True, db_column='MMNAV', max_length=5, null=True, validators=[infotor.validators.timespan_validator], verbose_name='Tempo Navetta'),
        ),
        migrations.AlterField(
            model_name='forra',
            name='pendenza',
            field=models.DecimalField(blank=True, db_column='PENDENZA', decimal_places=2, max_digits=5, null=True, verbose_name='Pendenza (%)'),
        ),
        migrations.AlterField(
            model_name='forra',
            name='quota_fine',
            field=models.DecimalField(blank=True, db_column='PERQUO2', decimal_places=0, max_digits=4, null=True, verbose_name='Quota Fine (slm)'),
        ),
        migrations.AlterField(
            model_name='forra',
            name='quota_inizio',
            field=models.DecimalField(blank=True, db_column='PERQUO1', decimal_places=0, max_digits=4, null=True, verbose_name='Quota Inizio (slm)'),
        ),
    ]
