# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0002_auto_20180804_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='forra',
            name='checkpoint1',
            field=models.ForeignKey(db_column='CHECKP1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint1', to='infotor.Checkpoint', verbose_name='Checkpoint 1'),
        ),
        migrations.AddField(
            model_name='forra',
            name='checkpoint2',
            field=models.ForeignKey(db_column='CHECKP2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint2', to='infotor.Checkpoint', verbose_name='Checkpoint 2'),
        ),
    ]
