# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0003_auto_20180804_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='forra',
            name='grado_impegno',
            field=models.ForeignKey(db_column='IMPTOR', default=1, on_delete=django.db.models.deletion.CASCADE, to='infotor.GradoImpegno', verbose_name='Grado Impegno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condizioni',
            name='codice',
            field=models.CharField(db_column='CODICE', max_length=3, primary_key=True, serialize=False, verbose_name='Codice'),
        ),
    ]
