# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0005_auto_20180805_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='codice',
            field=models.DecimalField(db_column='CODICE', decimal_places=0, max_digits=5, primary_key=True, serialize=False, verbose_name='Codice'),
        ),
        migrations.AlterField(
            model_name='litologia',
            name='codice',
            field=models.DecimalField(db_column='CODICE', decimal_places=0, max_digits=2, primary_key=True, serialize=False, verbose_name='Codice'),
        ),
        migrations.AlterField(
            model_name='mese',
            name='codice',
            field=models.DecimalField(db_column='CODICE', decimal_places=0, max_digits=2, primary_key=True, serialize=False, verbose_name='Codice'),
        ),
        migrations.AlterField(
            model_name='origineacqua',
            name='codice',
            field=models.DecimalField(db_column='CODICE', decimal_places=0, max_digits=2, primary_key=True, serialize=False, verbose_name='Codice'),
        ),
    ]
