# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infotor', '0006_auto_20180805_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='litologia',
            options={'ordering': ('descrizione',), 'verbose_name_plural': 'Litologie'},
        ),
        migrations.AlterModelOptions(
            name='mese',
            options={'ordering': ('codice',), 'verbose_name_plural': 'Mesi'},
        ),
        migrations.AlterModelOptions(
            name='operaidraulica',
            options={'ordering': ('descrizione',), 'verbose_name_plural': 'Opere Idrauliche'},
        ),
        migrations.AlterModelOptions(
            name='origineacqua',
            options={'ordering': ('descrizione',), 'verbose_name_plural': 'Origini Acqua'},
        ),
        migrations.AddField(
            model_name='forra',
            name='litologia',
            field=models.ForeignKey(db_column='LITOL', null=True, on_delete=django.db.models.deletion.CASCADE, to='infotor.Litologia', verbose_name='Litologia'),
        ),
        migrations.AddField(
            model_name='forra',
            name='opere_idrauliche',
            field=models.ForeignKey(db_column='OPEIDR', null=True, on_delete=django.db.models.deletion.CASCADE, to='infotor.OperaIdraulica', verbose_name='Opere Idrauliche'),
        ),
        migrations.AddField(
            model_name='forra',
            name='origine_acqua',
            field=models.ForeignKey(db_column='ORIGACQUA', null=True, on_delete=django.db.models.deletion.CASCADE, to='infotor.OrigineAcqua', verbose_name='Origine Acqua'),
        ),
        migrations.AddField(
            model_name='forra',
            name='stagionalita',
            field=models.ManyToManyField(db_column='STAGIONE', null=True, to='infotor.Mese', verbose_name='Mesi ok'),
        ),
    ]
